apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-api
  namespace: staging
spec:
  ingressClassName: nginx
  rules:
    - host: miapp-staging-api.local
      http:
        paths:
          - path: /weatherforecast
            pathType: Prefix
            backend:
              service:
                name: myapp-api
                port:
                  number: 80
