apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-api
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-api
  template:
    metadata:
      labels:
        app: myapp-api
    spec:
      # Mantén esto solo si tienes creado el secret en prod (si no, elimínalo):
      # imagePullSecrets:
      # - name: ghcr-pull-secret

      containers:
      - name: myapp-api
        # El workflow por TAGs reemplazará este valor con :sha-${{ github.sha }}
        image: ghcr.io/lcarbonell2026/myapp-api:sha-REEMPLAZAR_EN_PIPELINE
        ports:
        - containerPort: 80

        readinessProbe:
          httpGet:
            path: /weatherforecast
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /weatherforecast
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 5