apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: miapp-staging-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp-api
                port:
                  number: 80