apiVersion: v1
kind: Service
metadata:
  name: myapp-api
  namespace: staging
  labels:
    app: myapp-api
spec:
  type: ClusterIP
  selector:
    app: myapp-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
