name: STAGING - Deploy Kubernetes

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TestContainer   # ðŸ‘ˆ carpeta con tu Dockerfile y YAMLs
    steps:
      - uses: actions/checkout@v3

      - name: Login GHCR (con GITHUB_TOKEN)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image (staging)
        run: docker build -t ghcr.io/lcarbonell2026/myapp-api:staging .

      - name: Push image (staging)
        run: docker push ghcr.io/lcarbonell2026/myapp-api:staging

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TestContainer   # ðŸ‘ˆ aplicar manifiestos desde la misma carpeta
    steps:
      - uses: actions/checkout@v3

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configurar kubeconfig STAGING
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Aplicar manifiestos STAGING
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f ingress.yaml

      - name: Esperar rollout STAGING
        run: |
          kubectl -n staging rollout status deploy/myapp-api
          kubectl -n staging get pods -o wide