name: STAGING ‚Äì Build & Deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}

# üîê Imprescindible para publicar en GHCR con GITHUB_TOKEN
permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/myapp-api
  IMAGE_TAG: staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Diagn√≥stico
        run: ls -lahR .

      - name: Login GHCR (GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (carpeta TestContainer)
        uses: docker/build-push-action@v5
        with:
          context: ./TestContainer
          file: ./TestContainer/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v4

      - name: Aplicar manifiestos
        run: |
          kubectl -n staging apply -f TestContainer/deployment.yaml
          kubectl -n staging apply -f TestContainer/service.yaml
          kubectl -n staging apply -f TestContainer/ingress.yaml

      - name: Esperar rollout
        run: |
          kubectl -n staging rollout status deploy/myapp-api --timeout=180s
          kubectl -n staging get pods -o wide